const META_SHEET="_META",META_PREFIX_LOADNO="lastLoadNumber_",META_PREFIX_ROW="row_",META_PREFIX_SESSION="session_";
const SESSION_HOURS=18,MAX_PIN_FAILURES=8,LOCK_MINUTES=10;
const META_ROW_KEEP=1000,META_ROW_CLEAN_AT=1200;

function doGet(e){const a=String(e&&e.parameter&&e.parameter.action||"");return json_(a==="ping"?{ok:true,ts:new Date().toISOString()}:{ok:true,hint:"Use POST."})}
function doPost(e){try{const b=JSON.parse(e&&e.postData&&e.postData.contents||"{}"),a=String(b.action||"");if(a==="login")return login_(b);if(a==="listRecent")return listRecent_(b);if(a==="save"||!a)return save_(b);return json_({ok:false,error:"unknown_action"})}catch(err){return json_({ok:false,error:"exception",message:String(err)})}}

function login_(b){const auto=sanitizeSheetName_(b.auto),pin=String(b.pin||""),device=String(b.deviceKey||"");if(!auto)return json_({ok:false,error:"missing_auto"});if(!pin)return json_({ok:false,error:"missing_pin"});const props=PropertiesService.getScriptProperties(),cache=CacheService.getScriptCache(),failKey="pin_fail_"+auto+"_"+device,lockKey="pin_lock_"+auto+"_"+device;if(cache.get(lockKey))return json_({ok:false,error:"locked"});const wanted=props.getProperty("PIN_"+auto.replace(/[^A-Za-z0-9]/g,"_"));if(!wanted)return json_({ok:false,error:"pin_not_configured"});if(!safeEqual_(pin,wanted)){const n=Number(cache.get(failKey)||0)+1;cache.put(failKey,String(n),LOCK_MINUTES*60);if(n>=MAX_PIN_FAILURES){cache.put(lockKey,"1",LOCK_MINUTES*60);cache.remove(failKey);return json_({ok:false,error:"locked"})}return json_({ok:false,error:"bad_pin",attemptsLeft:MAX_PIN_FAILURES-n})}cache.remove(failKey);const token=Utilities.getUuid()+Utilities.getUuid(),expiresAt=Date.now()+SESSION_HOURS*3600000;props.setProperty(META_PREFIX_SESSION+hash_(token),JSON.stringify({auto:auto,expiresAt:expiresAt,deviceKey:device}));return json_({ok:true,auto:auto,sessionToken:token,expiresAt:expiresAt})}
function auth_(b){const token=String(b.sessionToken||"");if(!token)return{ok:false,error:"invalid_session"};const raw=PropertiesService.getScriptProperties().getProperty(META_PREFIX_SESSION+hash_(token));if(!raw)return{ok:false,error:"invalid_session"};try{const s=JSON.parse(raw);if(Number(s.expiresAt||0)<Date.now())return{ok:false,error:"invalid_session"};return{ok:true,auto:String(s.auto||"")}}catch(e){return{ok:false,error:"invalid_session"}}}

function listRecent_(b){const au=auth_(b);if(!au.ok)return json_(au);const requested=sanitizeSheetName_(b.auto);if(requested!==au.auto)return json_({ok:false,error:"wrong_vehicle"});const limit=Math.min(50,Math.max(1,Number(b.limit)||8)),rows=readVehicleRows_(requested).sort(function(x,y){return Number(y.savedMs||0)-Number(x.savedMs||0)}).slice(0,limit),savedKm=String(getMetaValue_("currentKm_"+requested)||""),currentKm=savedKm||(rows.length?String(rows[0].aloitusKm||""):""),next=peekNextLoadNumber_(requested);return json_({ok:true,rows:rows,currentKm:currentKm,nextLoadNo:next})}

function save_(b){const au=auth_(b);if(!au.ok)return json_(au);const auto=sanitizeSheetName_(b.auto||au.auto);if(auto!==au.auto)return json_({ok:false,error:"wrong_vehicle"});const pvm=String(b.lastausPvm||b.pvm||"").trim();if(!pvm)return json_({ok:false,error:"missing_pvm"});const ss=SpreadsheetApp.getActiveSpreadsheet(),tab=monthTabName_(pvm,auto),sh=getOrCreateSheet_(ss,tab);ensureHeaders_(sh);const uid=String(b.rowUid||"").trim(),meta=uid?getRowMeta_(uid):null,loadNo=meta&&meta.loadNo?String(meta.loadNo):String(b.loadNo||nextLoadNumber_(auto)),km=String(b.aloitusKm||getMetaValue_("currentKm_"+auto)||"").trim(),row=[loadNo,pvm,auto,km,String(b.r2||""),String(b.rahti||""),String(b.lastausPvm||pvm),String(b.lastausPaikka||""),String(b.purkuPvm||pvm),String(b.purkuPaikka||""),String(b.kuljettaja||""),String(b.maara||""),String(b.tonnit||""),String(b.tuote||""),String(b.huomio||""),new Date(),"PIN:"+auto,uid];let target=sh,rowNo=0;if(meta&&meta.tab&&meta.rowNumber){const old=ss.getSheetByName(String(meta.tab)),n=Number(meta.rowNumber)||0;if(old&&n>1){ensureHeaders_(old);if(old.getName()===tab){old.getRange(n,1,1,row.length).setValues([row]);target=old;rowNo=n}else{target.appendRow(row);rowNo=target.getLastRow();old.getRange(n,1,1,row.length).clearContent()}}}if(!rowNo){target.appendRow(row);rowNo=target.getLastRow()}if(uid){setRowMeta_(uid,{loadNo:loadNo,tab:target.getName(),rowNumber:rowNo});pruneRowMeta_()}if(km)setMetaValue_("currentKm_"+auto,km);const nextKm=String(b.nextKm||"").trim();if(nextKm)setMetaValue_("currentKm_"+auto,nextKm);return json_({ok:true,tab:target.getName(),loadNo:loadNo,currentKm:nextKm||km})}

function readVehicleRows_(auto){const ss=SpreadsheetApp.getActiveSpreadsheet(),out=[];ss.getSheets().forEach(function(sh){if(sh.getName()===META_SHEET||sh.getName().slice(-("__"+auto).length)!=="__"+auto||sh.getLastRow()<2)return;ensureHeaders_(sh);const vals=sh.getRange(2,1,sh.getLastRow()-1,18).getValues();vals.forEach(function(r){if(!String(r[0]||"").trim())return;const saved=r[15] instanceof Date?r[15].getTime():new Date(r[15]||0).getTime();out.push({loadNo:r[0],pvm:ymd_(r[1]),auto:r[2],aloitusKm:r[3],r2:r[4],rahti:r[5],lastausPvm:ymd_(r[6]),lastausPaikka:r[7],purkuPvm:ymd_(r[8]),purkuPaikka:r[9],kuljettaja:r[10],maara:r[11],tonnit:r[12],tuote:r[13],huomio:r[14],savedMs:isNaN(saved)?0:saved,rowUid:r[17]||"sheet_"+sh.getName()+"_"+(out.length+2)})})});return out}
function ymd_(v){if(v instanceof Date)return Utilities.formatDate(v,Session.getScriptTimeZone()||"Europe/Helsinki","yyyy-MM-dd");return String(v||"").slice(0,10)}
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function safeEqual_(a,b){a=String(a);b=String(b);let d=a.length^b.length,n=Math.max(a.length,b.length);for(let i=0;i<n;i++)d|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return d===0}
function hash_(s){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(s),Utilities.Charset.UTF_8).map(function(x){return("0"+(x&255).toString(16)).slice(-2)}).join("")}
function sanitizeSheetName_(s){return String(s||"").trim().replace(/[\[\]\:\*\?\/\\]/g,"-").replace(/\s+/g," ").slice(0,80)}
function parseYMD_(s){const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(String(s||""));return m?new Date(Number(m[1]),Number(m[2])-1,Number(m[3])):new Date()}
function monthTabName_(pvm,auto){const d=parseYMD_(pvm);return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"__"+auto}
function getOrCreateSheet_(ss,n){return ss.getSheetByName(n)||ss.insertSheet(n)}
function ensureHeaders_(sh){const h=["Kuorma #","Päivämäärä","Auto nro","Aloitus km","R2 / Asiakas","Rahtikirja","Lastaus pvm","Lastauspaikka","Purku pvm","Purku paikka","Kuljettaja","Määrä (m³)","Tonnit","Tuote","Muuta huomioitavaa","Tallennettu","Käyttäjä","Rivitunniste"];if(sh.getLastRow()>0&&String(sh.getRange(1,15).getValue())==="Tallennettu")sh.insertColumnBefore(15);if(sh.getMaxColumns()<h.length)sh.insertColumnsAfter(sh.getMaxColumns(),h.length-sh.getMaxColumns());if(sh.getLastRow()===0)sh.getRange(1,1,1,h.length).setValues([h]);else{const r=sh.getRange(1,1,1,h.length).getValues()[0],empty=r.every(function(x){return String(x||"")===""});if(empty)sh.getRange(1,1,1,h.length).setValues([h]);else if(String(r[0])!==h[0]){sh.insertRowBefore(1);sh.getRange(1,1,1,h.length).setValues([h])}else sh.getRange(1,1,1,h.length).setValues([h])}sh.getRange(1,1,1,h.length).setFontWeight("bold");sh.setFrozenRows(1)}
function ensureMetaHeaders_(sh){if(sh.getLastRow()===0)sh.getRange(1,1,1,2).setValues([["key","value"]]);else{const r=sh.getRange(1,1,1,2).getValues()[0];if(String(r[0])!=="key"){sh.insertRowBefore(1);sh.getRange(1,1,1,2).setValues([["key","value"]])}}sh.getRange(1,1,1,2).setFontWeight("bold");sh.setFrozenRows(1)}
function getMetaValue_(key){const ss=SpreadsheetApp.getActiveSpreadsheet(),sh=ss.getSheetByName(META_SHEET)||ss.insertSheet(META_SHEET);ensureMetaHeaders_(sh);const v=sh.getDataRange().getValues();for(let i=1;i<v.length;i++)if(String(v[i][0])===String(key))return String(v[i][1]||"");return""}
function setMetaValue_(key,value){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const ss=SpreadsheetApp.getActiveSpreadsheet(),sh=ss.getSheetByName(META_SHEET)||ss.insertSheet(META_SHEET);ensureMetaHeaders_(sh);const v=sh.getDataRange().getValues();for(let i=1;i<v.length;i++)if(String(v[i][0])===String(key)){sh.getRange(i+1,2).setValue(String(value||""));return}sh.appendRow([String(key),String(value||"")])}finally{lock.releaseLock()}}
function getRowMeta_(uid){const raw=getMetaValue_(META_PREFIX_ROW+uid);if(!raw)return null;try{return JSON.parse(raw)}catch(e){return null}}
function setRowMeta_(uid,m){setMetaValue_(META_PREFIX_ROW+uid,JSON.stringify(m))}
function pruneRowMeta_(){const cache=CacheService.getScriptCache(),cacheKey="meta_row_prune_checked";if(cache.get(cacheKey))return;cache.put(cacheKey,"1",600);const lock=LockService.getScriptLock();lock.waitLock(30000);try{const sh=SpreadsheetApp.getActiveSpreadsheet().getSheetByName(META_SHEET);if(!sh||sh.getLastRow()<META_ROW_CLEAN_AT+2)return;ensureMetaHeaders_(sh);const keys=sh.getRange(2,1,sh.getLastRow()-1,1).getValues(),rowNumbers=[];keys.forEach(function(r,i){if(String(r[0]||"").indexOf(META_PREFIX_ROW)===0)rowNumbers.push(i+2)});if(rowNumbers.length<=META_ROW_CLEAN_AT)return;const remove=rowNumbers.slice(0,rowNumbers.length-META_ROW_KEEP);for(let i=remove.length-1;i>=0;){let end=remove[i],start=end;i--;while(i>=0&&remove[i]===start-1){start=remove[i];i--}sh.deleteRows(start,end-start+1)}}finally{lock.releaseLock()}}
function peekNextLoadNumber_(auto){return(Number(getMetaValue_(META_PREFIX_LOADNO+auto))||0)+1}
function nextLoadNumber_(auto){const lock=LockService.getScriptLock();lock.waitLock(30000);try{const ss=SpreadsheetApp.getActiveSpreadsheet(),sh=ss.getSheetByName(META_SHEET)||ss.insertSheet(META_SHEET);ensureMetaHeaders_(sh);const key=META_PREFIX_LOADNO+auto,v=sh.getDataRange().getValues();let row=0,current=0;for(let i=1;i<v.length;i++)if(String(v[i][0])===key){row=i+1;current=Number(v[i][1])||0;break}if(!row){row=sh.getLastRow()+1;sh.getRange(row,1,1,2).setValues([[key,0]])}const next=current+1;sh.getRange(row,2).setValue(next);return next}finally{lock.releaseLock()}}

// Lisää yksityiset PIN-koodit Apps Scriptin asetuksissa:
// PIN_ISS_440 ja PIN_GPG_830. Älä kirjoita PIN-koodeja tähän julkiseen tiedostoon.
