Queue serialization checks OK
const API_URL="https://script.google.com/macros/s/AKfycbzPnC8CiCZjfHE2UlbG_i38x_dHL-JYt-essUssKaoAjao31kdaCRKVD1R7RqiLYhPQ/exec";
const SESSION_KEY="kuljetuskirjaus_session_v1",QUEUE_KEY="kuljetuskirjaus_queue_v1",SUGGEST_KEY="kuljetuskirjaus_suggestions_v1",DRIVER_KEY="kuljetuskirjaus_driver_v1";
const $=id=>document.getElementById(id);let session=null,recent=[],pendingSave=null,kmMode="next",flushing=false;
document.addEventListener("DOMContentLoaded",init);
function today(){const d=new Date(),o=d.getTimezoneOffset();return new Date(d.getTime()-o*60000).toISOString().slice(0,10)}
function deviceKey(){let k=localStorage.getItem("kuljetuskirjaus_device_v1");if(!k){k="d_"+crypto.randomUUID();localStorage.setItem("kuljetuskirjaus_device_v1",k)}return k}
function getSession(){try{const s=JSON.parse(localStorage.getItem(SESSION_KEY)||"null");return s&&s.expiresAt>Date.now()?s:null}catch{return null}}
function saveSession(s){session=s;localStorage.setItem(SESSION_KEY,JSON.stringify(s))}
function init(){session=getSession();bind();setDates();loadSuggestions();$("kuljettaja").value=localStorage.getItem(DRIVER_KEY)||"Juha";if(session)openApp();else showLogin()}
function bind(){$("loginBtn").onclick=login;$("loadForm").onsubmit=e=>{e.preventDefault();prepareSave()};$("refreshBtn").onclick=loadRecent;$("retryBtn").onclick=flushQueue;$("logoutBtn").onclick=logout;$("kmCancelBtn").onclick=closeKm;$("kmSaveBtn").onclick=confirmKm;window.addEventListener("online",flushQueue)}
function setDates(){$("lastausPvm").value=today();$("purkuPvm").value=today()}
function showLogin(){$("loginView").classList.remove("hidden");$("mainView").classList.add("hidden")}
async function login(){const auto=$("loginAuto").value,pin=$("pin").value.trim();if(!pin)return msg("loginStatus","Anna PIN-koodi.","error");busy("loginBtn",true);msg("loginStatus","Kirjaudutaan…","wait");try{const r=await api({action:"login",auto,pin,deviceKey:deviceKey()});if(!r.ok)throw new Error(errorText(r.error));saveSession({auto:r.auto,token:r.sessionToken,expiresAt:Number(r.expiresAt)});$("pin").value="";openApp()}catch(e){msg("loginStatus",e.message,"error")}finally{busy("loginBtn",false)}}
function openApp(){$("loginView").classList.add("hidden");$("mainView").classList.remove("hidden");$("currentAuto").textContent=session.auto;loadRecent();flushQueue()}
function logout(){localStorage.removeItem(SESSION_KEY);session=null;recent=[];showLogin()}
async function loadRecent(){if(!session)return;try{const r=await api({action:"listRecent",auto:session.auto,sessionToken:session.token,limit:8});if(!r.ok)throw new Error(errorText(r.error));recent=Array.isArray(r.rows)?r.rows:[];$("currentKm").textContent=r.currentKm||"—";$("nextLoadNo").textContent="Kuorma "+(r.nextLoadNo||"—");render();msg("saveStatus","","")}catch(e){if(e.message.includes("Kirjautuminen"))logout();else msg("saveStatus","Kuormien haku epäonnistui: "+e.message,"error")}}
function formData(){return{r2:v("r2"),rahti:v("rahti"),lastausPvm:v("lastausPvm"),lastausPaikka:v("lastausPaikka"),purkuPvm:v("purkuPvm"),purkuPaikka:v("purkuPaikka"),kuljettaja:v("kuljettaja"),maara:v("maara"),tonnit:v("tonnit"),tuote:v("tuote")}}
function v(id){return String($(id).value||"").trim()}
function prepareSave(){const d=formData();if(!d.r2&&!d.rahti&&!d.lastausPaikka&&!d.purkuPaikka)return msg("saveStatus","Täytä kuorman tiedot.","error");const groupCount=countCurrentKmRows(),km=String($("currentKm").textContent||"").trim();pendingSave={...d,rowUid:"row_"+crypto.randomUUID(),createdAt:Date.now(),status:"pending"};if(!km||km==="—")openKm("current");else if(groupCount>=5)openKm("next");else commitSave("")}
function openKm(mode){kmMode=mode;$("kmTitle").textContent=mode==="current"?"Anna aloituskilometrit":"Kuusi kuormaa täynnä";$("kmPromptText").textContent=mode==="current"?"Anna tämän ja seuraavien viiden kuorman aloituskilometrit.":"Anna seuraavien kuuden kuorman aloituskilometrit.";$("nextKmInput").value="";$("kmModal").classList.remove("hidden");$("nextKmInput").focus()}
function countCurrentKmRows(){const km=String($("currentKm").textContent||"").trim();if(!km||km==="—")return 0;const q=queue().slice().reverse(),seen=new Set(q.map(x=>x.rowUid)),all=[...q,...recent.filter(x=>!seen.has(x.rowUid))];let n=0;for(const r of all){if(String(r.aloitusKm||"").trim()===km)n++;else break}return n}
function closeKm(){pendingSave=null;$("kmModal").classList.add("hidden")}
function confirmKm(){const km=v("nextKmInput");if(!km)return;$("kmModal").classList.add("hidden");if(kmMode==="current"){$("currentKm").textContent=km;commitSave("")}else commitSave(km)}
async function commitSave(nextKm){const item={...pendingSave,auto:session.auto,aloitusKm:$("currentKm").textContent==="—"?"":$("currentKm").textContent,nextKm};pendingSave=null;queueAdd(item);recent=[item,...recent].slice(0,8);render();resetForm();msg("saveStatus","Kuorma lisätty. Lähetetään Sheetsiin…","wait");await flushQueue()}
function resetForm(){["r2","rahti","lastausPaikka","purkuPaikka","maara","tonnit","tuote"].forEach(id=>$(id).value="");localStorage.setItem(DRIVER_KEY,v("kuljettaja"));setDates()}
function queue(){try{return JSON.parse(localStorage.getItem(QUEUE_KEY)||"[]")}catch{return[]}}
function queueAdd(x){const q=queue();q.push(x);localStorage.setItem(QUEUE_KEY,JSON.stringify(q));saveSuggestions(x)}
async function flushQueue(){if(flushing||!session||!navigator.onLine)return;let q=queue();if(!q.length)return;flushing=true;try{for(const item of [...q]){try{const r=await api({action:"save",sessionToken:session.token,...item});if(!r.ok)throw new Error(errorText(r.error));q=q.filter(x=>x.rowUid!==item.rowUid);localStorage.setItem(QUEUE_KEY,JSON.stringify(q));msg("saveStatus","Tallennettu Sheetsiin.","ok")}catch(e){item.status="fail";localStorage.setItem(QUEUE_KEY,JSON.stringify(q));msg("saveStatus","Tallennus odottaa yhteyttä: "+e.message,"error");break}}await loadRecent()}finally{flushing=false;if(queue().length&&session&&navigator.onLine)setTimeout(flushQueue,1000)}}
function render(){const q=queue(),queued=new Map(q.map(x=>[x.rowUid,x]));const merged=[...q.slice().reverse(),...recent.filter(r=>!queued.has(r.rowUid))].slice(0,8),box=$("recentLoads");box.innerHTML='<div class="load-row header"><span>Kuorma</span><span>Päivä</span><span>R2</span><span>Lastaus</span><span>Purku</span><span>Kuljettaja</span><span>Tuote</span><span>Tila</span></div>';if(!merged.length){box.innerHTML+='<div class="empty">Ei tallennettuja kuormia.</div>';return}for(const r of merged){const st=queued.has(r.rowUid)?(r.status==="fail"?"fail":"pending"):"ok",sym=st==="ok"?"✓":st==="fail"?"!":"…";box.insertAdjacentHTML("beforeend",`<div class="load-row"><div><div class="load-main">#${esc(r.loadNo||"—")}</div><div class="load-sub">${esc(r.aloitusKm||"")} km</div></div><div>${esc(dateFi(r.lastausPvm||r.pvm))}</div><div>${esc(r.r2||"")}</div><div><div class="load-main">${esc(r.lastausPaikka||"")}</div><div class="load-sub">${esc(r.rahti||"")}</div></div><div><div class="load-main">${esc(r.purkuPaikka||"")}</div><div class="load-sub">${esc(r.maara||"")} m³ · ${esc(r.tonnit||"")} t</div></div><div>${esc(r.kuljettaja||"")}</div><div>${esc(r.tuote||"")}</div><div class="state ${st}">${sym}</div></div>`)}}
async function api(body){const c=new AbortController(),t=setTimeout(()=>c.abort(),35000);try{const res=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(body),signal:c.signal}),text=await res.text();let data;try{data=JSON.parse(text)}catch{const html=/^\s*</.test(text);throw new Error(html?"Apps Script palautti verkkosivun JSON-vastauksen sijasta. Yritä uudelleen; jos virhe toistuu, tarkista verkkosovelluksen käyttöönotto.":"Apps Script palautti virheellisen vastauksen.")}if(!res.ok)throw new Error(data.message||errorText(data.error)||("HTTP "+res.status));return data}catch(e){if(e&&e.name==="AbortError")throw new Error("Apps Script ei vastannut 35 sekunnissa.");throw e}finally{clearTimeout(t)}}
function saveSuggestions(d){let s;try{s=JSON.parse(localStorage.getItem(SUGGEST_KEY)||"{}") }catch{s={}};[["lastaus",d.lastausPaikka],["purku",d.purkuPaikka],["tuote",d.tuote]].forEach(([k,x])=>{if(x)s[k]=[...new Set([...(s[k]||[]),x])].slice(-30)});localStorage.setItem(SUGGEST_KEY,JSON.stringify(s));loadSuggestions()}
function loadSuggestions(){let s;try{s=JSON.parse(localStorage.getItem(SUGGEST_KEY)||"{}") }catch{s={}};[["lastausList",s.lastaus],["purkuList",s.purku],["tuoteList",s.tuote]].forEach(([id,a])=>$(id).innerHTML=(a||[]).map(x=>`<option value="${esc(x)}">`).join(""))}
function msg(id,text,type){const e=$(id);e.textContent=text;e.className="message "+(type||"")}
function busy(id,on){$(id).disabled=on}
function dateFi(x){const m=/^(\d{4})-(\d{2})-(\d{2})/.exec(x||"");return m?`${m[3]}.${m[2]}.${m[1]}`:(x||"")}
function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function errorText(e){return({bad_pin:"Väärä PIN-koodi.",locked:"Liian monta yritystä. Odota 10 minuuttia.",missing_pin:"PIN-koodi puuttuu.",missing_auth:"Apps Scriptissä on vielä vanha kirjautumisversio. Kopioi uusi koodi.gs ja julkaise uusi versio.",pin_not_configured:"Auton PIN-koodia ei ole asetettu Apps Scriptiin.",invalid_session:"Kirjautuminen on vanhentunut.",wrong_vehicle:"Istunto kuuluu toiselle autolle."})[e]||String(e||"Tuntematon virhe")}
